name: CI

on:
  pull_request:
    branches:
    - task-12

jobs:
  build:
    name: Build and Test AWS CDK Typescript Stack
    runs-on: ubuntu-latest
    steps:
      - name: Initiated By User
        run: echo $GITHUB_ACTOR

      - name: Check Out Code
        uses: actions/checkout@v3.1.0

      - name: Install Node
        uses: actions/setup-node@v3.5.0
        with:
          node-version: '20'

      - name: Enable Corepack
        run: corepack enable
      
      - name: Install pnpm 
        run: corepack prepare pnpm@latest --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --config.dedupe-peer-dependents=false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1 
      
      - name: Run Makefile to build and deploy
        env:
          STAGE: env
        run: make deploy