name: dev-deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy development environment
    uses: flaviostutz/gh-makefile/.github/workflows/make-ci.yml@main
    with:
      working-directory: ./
      tooling: node
      tooling-version: 16
      stage: dev
      target-build: true
      target-lint: true
      target-unit-tests: true
      target-deploy: true
      environment: dev
      AWS_DEFAULT_REGION: us-east-1
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}